#!/bin/bash
# Sidekick screensaver script with enhanced activity detection including touchpad
# Auto-generated by PyQt6 Screensaver Preferences GUI - Fixed for SSH+Wayland

echo "🟢💚 Starting Sidekick Digital Rain on All displays..."

# Check if we should only run on physical screens
PHYSICAL_ONLY=true

if [ "$PHYSICAL_ONLY" = "true" ]; then
    # Check for physical displays - allow SSH management but require local display capability
    # Look for connected physical displays via DRM/framebuffer
    PHYSICAL_DISPLAY_FOUND=false

    # Check for connected HDMI displays via DRM
    if [ -d "/sys/class/drm" ]; then
        for status_file in /sys/class/drm/card*/status; do
            if [ -f "$status_file" ] && grep -q "connected" "$status_file" 2>/dev/null; then
                PHYSICAL_DISPLAY_FOUND=true
                break
            fi
        done
    fi

    # Check for framebuffer devices as backup
    if [ "$PHYSICAL_DISPLAY_FOUND" = "false" ] && [ -c "/dev/fb0" ]; then
        PHYSICAL_DISPLAY_FOUND=true
    fi

    # Allow if we have physical displays, even via SSH (for Pi management)
    if [ "$PHYSICAL_DISPLAY_FOUND" = "false" ]; then
        echo "🚫 Skipping Sidekick - no physical displays detected"
        exit 0
    fi

    echo "✅ Physical display confirmed - proceeding with Sidekick..."
fi

# Function to cleanup on exit
cleanup() {
    pkill -f "sidekick_widget.py" 2>/dev/null
    pkill -f "mystify_widget.py" 2>/dev/null
    pkill -f "slideshow_widget.py" 2>/dev/null
    exit 0
}

trap cleanup EXIT

# Use swayidle for Wayland environment
# Default screensaver timeout: 5 minutes (300 seconds)
# Default display timeout: 10 minutes (600 seconds)

echo "🟢 Starting Wayland Sidekick Screensaver System..."
echo "Timeline:"
echo "  0-5 min:  Normal desktop"
echo "  5-10 min: Sidekick digital rain (moving graphics)"
echo "  10+ min:  Screen off (power saving)"
echo ""

# The complete screensaver recipe with proper Wayland environment
SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
export WAYLAND_DISPLAY=wayland-0
swayidle -w \
    timeout 300 "echo 'Entering the Sidekick...' && cd '$SCRIPT_DIR' && bash sidekick_screensaver.sh" \
    timeout 600 "echo 'Powering down all displays...' && pkill -f sidekick_widget.py; pkill -f mystify_widget.py; pkill -f slideshow_widget.py; pkill -f video_widget.py; export WAYLAND_DISPLAY=wayland-0 && wlopm --off '*' 2>/dev/null || xset dpms force off" \
    resume "echo 'Exiting the Sidekick...' && pkill -f sidekick_widget.py; pkill -f mystify_widget.py; pkill -f slideshow_widget.py; pkill -f video_widget.py; export WAYLAND_DISPLAY=wayland-0 && wlopm --on '*' 2>/dev/null || xset dpms force on" \
    before-sleep "echo 'System sleeping - killing Sidekick...' && pkill -f sidekick_widget.py; pkill -f mystify_widget.py; pkill -f slideshow_widget.py; pkill -f video_widget.py; export WAYLAND_DISPLAY=wayland-0 && wlopm --off '*' 2>/dev/null || xset dpms force off"
